services:
  wordpress:
    build: ./wordpress
    container_name: wordpress
    ports:
      - 8090:80
    env_file:
      - ./env/wordpress.env
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: mysql-server
    env_file:
      - ./env/mysql.env
    volumes:
      - ./db:/var/lib/mysql
      - ./data/:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "--password=pass",
        ]
      interval: 10s
      timeout: 10s
      retries: 6

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8082:80
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

volumes:
  wordpress:
  db:

networks:
  app-network:
