FROM wordpress:latest
RUN apt-get update && apt-get install -y \
    less \
    vim \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html
COPY . /var/www/html
RUN chown -R www-data:www-data /var/www/html
EXPOSE 80
